name: Build and Upload Binary
on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      ext:
        required: true
        type: string
      os_name:
        required: true
        type: string
      os:
        required: true
        type: string
      go_version:
        required: false
        default: "^1.23.2"
        type: string
      env:
        required: false
        default: ""
        type: string

jobs:
  build:
    name: 🧱 Build 🧱
    runs-on: ${{ inputs.os }}
    defaults:
      run:
        shell: bash
    steps:
      # -----------------------------------------------------------
      # Info
      # -----------------------------------------------------------
      - name: 📋 Info 📋
        run: |
          echo "Running for ${{ inputs.os_name }}"

      # -----------------------------------------------------------
      # Checkout the repository
      # -----------------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -----------------------------------------------------------
      # Parse and export environment variables
      # -----------------------------------------------------------
      - name: Set environment variables
        run: |
          echo "${{ inputs.env }}" | while IFS= read -r line; do
            if [ -n "$line" ]; then
              echo "Exporting $line"
              export "$line"
              echo "$line" >> $GITHUB_ENV
            fi
          done

      #--------------------------------------------------------------------
      # Install Go
      #--------------------------------------------------------------------
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
      #--------------------------------------------------------------------
      - run: go version
      #--------------------------------------------------------------------

      #--------------------------------------------------------------------
      # client_secret.json
      #--------------------------------------------------------------------
      - name: Client secrets
        run: |
          echo '${{ secrets.GOOGLE_CLIENT_SECRET }}' > ./client_secret.json

      #--------------------------------------------------------------------
      # Download dependencies
      #--------------------------------------------------------------------
      - run: ./scripts/mod.download.sh
      #--------------------------------------------------------------------
      - run: ./scripts/mod.verify.sh
      #--------------------------------------------------------------------
      - run: ./scripts/mod.tidy.sh

      #--------------------------------------------------------------------
      # Build the binary
      #--------------------------------------------------------------------
      - run: ./scripts/build.sh
      #--------------------------------------------------------------------
      #--------------------------------------------------------------------
      - run: mv ./dist/gcnf ./dist/${{ inputs.file }}
      #--------------------------------------------------------------------

      #--------------------------------------------------------------------
      # Upload the binary
      #--------------------------------------------------------------------
      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.file }}
          path: dist/${{ inputs.file }}
      #--------------------------------------------------------------------
      - name: Clean Up
        run: rm -rf build, dist
      #--------------------------------------------------------------------
