name: Build
permissions:
  contents: write
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  #----------------------------------------------------------------
  prepare:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      build: ${{ github.run_number }}
      version: ${{ steps.project.outputs.version }}-${{ github.run_number }}
      name: ${{ steps.project.outputs.name }}
    steps:
      #------------------------------------------------------------
      # Checkout the repository
      #------------------------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4
      #------------------------------------------------------------
      - name: Project
        id: project
        run: |
          echo "name=$(./scripts/get.property.sh --property name --file ./project.properties)" >> "$GITHUB_OUTPUT"
          echo "version=$(./scripts/get.property.sh --property version --file ./project.properties)" >> "$GITHUB_OUTPUT"

      #------------------------------------------------------------
      - name: 📥 Info 📥
        run: |
          VERSION_FULL=${{ steps.project.outputs.version }}-${{ github.run_number }}
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "### BUILD INFO" >> $GITHUB_STEP_SUMMARY
          echo "| Name          | Value                              |" >> $GITHUB_STEP_SUMMARY
          echo "| :------------ | :--------------------------------- |" >> $GITHUB_STEP_SUMMARY
          echo "| project       | ${{ steps.project.outputs.name }}  |" >> $GITHUB_STEP_SUMMARY | cat
          echo "| version       | $VERSION_FULL                      |" >> $GITHUB_STEP_SUMMARY | cat
          echo "| branch        | ${{ github.ref }}                  |" >> $GITHUB_STEP_SUMMARY | cat
          echo "| sha           | ${{ github.sha }}                  |" >> $GITHUB_STEP_SUMMARY | cat
          echo "| build         | ${{ github.run_number }}           |" >> $GITHUB_STEP_SUMMARY | cat
          echo "---" >> $GITHUB_STEP_SUMMARY
  #----------------------------------------------------------------
  build_linux_arm64:
    name: 🧱 Build For Linux 🧱
    needs:
      - prepare
    uses: ./.github/workflows/action-build-and-release.yml
    with:
      file: gcnf-linux-arm64
      os_name: linux
      os: ubuntu-24.04-arm64
      ext: ""
      env: |
        GOCACHE='/home/runner/.cache/go-build'
    secrets: inherit
  #----------------------------------------------------------------
  build_linux_amd64:
    name: 🧱 Build For Linux 🧱
    needs:
      - prepare
    uses: ./.github/workflows/action-build-and-release.yml
    with:
      file: gcnf-linux-amd64
      os_name: linux
      os: ubuntu-24.04
      ext: ""
    secrets: inherit
  #----------------------------------------------------------------
  build_windows:
    name: 🧱 Build For Windows 🧱
    needs:
      - prepare
    uses: ./.github/workflows/action-build-and-release.yml
    with:
      file: gcnf-windows.exe
      os_name: windows
      os: windows-latest
      ext: ".exe"
    secrets: inherit
  #----------------------------------------------------------------
  build_darwin_arm64:
    name: 🧱 Build For Darwin arm64 🧱
    needs:
      - prepare
    uses: ./.github/workflows/action-build-and-release.yml
    with:
      file: gcnf-darwin-arm64
      os_name: darwin-arm64
      os: macos-14
      ext: ""
    secrets: inherit
  #----------------------------------------------------------------
  build_darwin_amd64:
    name: 🧱 Build For Darwin amd64 🧱
    needs:
      - prepare
    uses: ./.github/workflows/action-build-and-release.yml
    with:
      file: gcnf-darwin-amd64
      os_name: darwin-amd64
      os: macos-13
      ext: ""
    secrets: inherit
  #----------------------------------------------------------------
  release:
    name: 🚀 Release 🚀
    needs:
      - prepare
      - build_linux_amd64
      - build_linux_arm64
      - build_windows
      - build_darwin_arm64
      - build_darwin_amd64
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------------------------
      - name: Download Linux ARM64 Binary
        uses: actions/download-artifact@v4
        with:
          name: gcnf-linux-arm64
          path: build/linux/
      #----------------------------------------------------------------
      - name: Download Linux AMD64 Binary
        uses: actions/download-artifact@v4
        with:
          name: gcnf-linux-amd64
          path: build/linux/
      #----------------------------------------------------------------
      - name: Download Windows Binary
        uses: actions/download-artifact@v4
        with:
          name: gcnf-windows.exe
          path: build/windows/
      #----------------------------------------------------------------
      - name: Download Darwin ARM64 Binary
        uses: actions/download-artifact@v4
        with:
          name: gcnf-darwin-arm64
          path: build/darwin/
      #----------------------------------------------------------------
      - name: Download Darwin AMD64 Binary
        uses: actions/download-artifact@v4
        with:
          name: gcnf-darwin-amd64
          path: build/darwin/
      #----------------------------------------------------------------
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ needs.prepare.outputs.version }}"
          release_name: "Release v${{ needs.prepare.outputs.version }}"
          body: |
            Automated release for the latest push to master.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #----------------------------------------------------------------
      - name: Upload Linux ARM64 Binary to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/linux/gcnf-linux-arm64
          asset_name: gcnf-linux-arm64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #----------------------------------------------------------------
      - name: Upload Linux AMD64 Binary to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/linux/gcnf-linux-amd64
          asset_name: gcnf-linux-amd64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #----------------------------------------------------------------
      - name: Upload Windows Binary to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/windows/gcnf-windows.exe
          asset_name: gcnf-windows.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #----------------------------------------------------------------
      - name: Upload Darwin ARM64 Binary to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/darwin/gcnf-darwin-arm64
          asset_name: gcnf-darwin-arm64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #----------------------------------------------------------------
      - name: Upload Darwin AMD64 Binary to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/darwin/gcnf-darwin-amd64
          asset_name: gcnf-darwin-amd64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #----------------------------------------------------------------
  final:
    name: 🏁 Final 🏁
    runs-on: ubuntu-latest
    needs: release
    defaults:
      run:
        shell: bash
    steps:
      #------------------------------------------------------------
      # Checkout the repository
      #------------------------------------------------------------
      - run: echo "Final step"
