name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  GO_VERSION: 1.25.0

jobs:
  #----------------------------------------------------------------
  prepare:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    outputs:
      go_version: ${{ env.GO_VERSION }}
      build: ${{ github.run_number }}
      version: ${{ steps.project.outputs.version }}-${{ github.run_number }}
      name: ${{ steps.project.outputs.name }}
    steps:
      #------------------------------------------------------------
      # Checkout the repository
      #------------------------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      #------------------------------------------------------------
      # Set up Project
      #------------------------------------------------------------
      - name: Project
        id: project
        run: |
          echo "name=$(./scripts/get.property.sh --property name --file ./project.properties)" >> "$GITHUB_OUTPUT"
          echo "version=$(./scripts/get.property.sh --property version --file ./project.properties)" >> "$GITHUB_OUTPUT"

      #------------------------------------------------------------
      # Info
      #------------------------------------------------------------
      - name: 📥 Info 📥
        run: |
          VERSION_FULL=${{ steps.project.outputs.version }}-${{ github.run_number }}
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "### BUILD INFO" >> $GITHUB_STEP_SUMMARY
          echo "| Name          | Value                              |" >> $GITHUB_STEP_SUMMARY
          echo "| :------------ | :--------------------------------- |" >> $GITHUB_STEP_SUMMARY
          echo "| project       | ${{ steps.project.outputs.name }}  |" >> $GITHUB_STEP_SUMMARY
          echo "| version       | $VERSION_FULL                      |" >> $GITHUB_STEP_SUMMARY
          echo "| branch        | ${{ github.ref }}                  |" >> $GITHUB_STEP_SUMMARY
          echo "| sha           | ${{ github.sha }}                  |" >> $GITHUB_STEP_SUMMARY
          echo "| build         | ${{ github.run_number }}           |" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY

  #----------------------------------------------------------------
  # BUILD
  #----------------------------------------------------------------
  build_linux_arm64:
    name: 🧱 Build For Linux 🧱
    needs:
      - prepare
    uses: ./.github/workflows/action-build-and-release.yml
    with:
      file: gcnf-linux-arm64
      os_name: linux
      os: ubuntu-24.04-arm64
      ext: ""
      go_version: ${{ needs.prepare.outputs.go_version }}
      env: |
        GOPATH=/root/actions-runner/_work/_tool/go/${{ needs.prepare.outputs.go_version }}/arm64
        GOCACHE=$GOPATH/cache
        GOMODCACHE=$GOPATH/pkg/mod
    secrets: inherit
  #----------------------------------------------------------------
  build_linux_amd64:
    name: 🧱 Build For Linux 🧱
    needs:
      - prepare
    uses: ./.github/workflows/action-build-and-release.yml
    with:
      file: gcnf-linux-amd64
      os_name: linux
      os: ubuntu-24.04
      go_version: ${{ needs.prepare.outputs.go_version }}
      ext: ""
    secrets: inherit
  #----------------------------------------------------------------
  build_windows:
    name: 🧱 Build For Windows 🧱
    needs:
      - prepare
    uses: ./.github/workflows/action-build-and-release.yml
    with:
      file: gcnf-windows.exe
      os_name: windows
      os: windows-latest
      go_version: ${{ needs.prepare.outputs.go_version }}
      ext: ".exe"
    secrets: inherit
  #----------------------------------------------------------------
  build_darwin_arm64:
    name: 🧱 Build For Darwin arm64 🧱
    needs:
      - prepare
    uses: ./.github/workflows/action-build-and-release.yml
    with:
      file: gcnf-darwin-arm64
      os_name: darwin-arm64
      os: macos-14
      go_version: ${{ needs.prepare.outputs.go_version}}
      ext: ""
    secrets: inherit
  #----------------------------------------------------------------
  build_darwin_amd64:
    name: 🧱 Build For Darwin amd64 🧱
    needs:
      - prepare
    uses: ./.github/workflows/action-build-and-release.yml
    with:
      file: gcnf-darwin-amd64
      os_name: darwin-amd64
      os: macos-13
      go_version: ${{ needs.prepare.outputs.go_version }}
      ext: ""
    secrets: inherit

  #----------------------------------------------------------------
  # RELEASE
  #----------------------------------------------------------------
  release:
    name: 🚀 Release 🚀
    permissions:
      contents: write
    needs:
      - prepare
      - build_linux_amd64
      - build_linux_arm64
      - build_windows
      - build_darwin_arm64
      - build_darwin_amd64
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------------------------
      - name: Download Linux ARM64 Binary
        uses: actions/download-artifact@v4
        with:
          name: gcnf-linux-arm64
          path: build/linux/
      #----------------------------------------------------------------
      - name: Download Linux AMD64 Binary
        uses: actions/download-artifact@v4
        with:
          name: gcnf-linux-amd64
          path: build/linux/
      #----------------------------------------------------------------
      - name: Download Windows Binary
        uses: actions/download-artifact@v4
        with:
          name: gcnf-windows.exe
          path: build/windows/
      #----------------------------------------------------------------
      - name: Download Darwin ARM64 Binary
        uses: actions/download-artifact@v4
        with:
          name: gcnf-darwin-arm64
          path: build/darwin/
      #----------------------------------------------------------------
      - name: Download Darwin AMD64 Binary
        uses: actions/download-artifact@v4
        with:
          name: gcnf-darwin-amd64
          path: build/darwin/
      #----------------------------------------------------------------
      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.prepare.outputs.version }}"
          name: "Release v${{ needs.prepare.outputs.version }}"
          body: |
            Automated release for the latest push to master.
          draft: false
          prerelease: false
          files: |
            build/linux/gcnf-linux-arm64
            build/linux/gcnf-linux-amd64
            build/windows/gcnf-windows.exe
            build/darwin/gcnf-darwin-arm64
            build/darwin/gcnf-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #----------------------------------------------------------------
  final:
    name: 🏁 Final 🏁
    runs-on: ubuntu-latest
    needs: release
    defaults:
      run:
        shell: bash
    steps:
      #------------------------------------------------------------
      # Checkout the repository
      #------------------------------------------------------------
      - run: echo "Final step"
