name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  GCNF_GOOGLE_CREDENTIAL_BASE64: ${{ secrets.GCNF_GOOGLE_CREDENTIAL_BASE64 }}
  GCNF_GOOGLE_SHEET_ID: ${{ secrets.GCNF_GOOGLE_SHEET_ID }}
  GCNF_GOOGLE_SHEET_NAME: ${{ secrets.GCNF_GOOGLE_SHEET_NAME }}
  GCNF_STORE_CONFIG_FILE: ./tmp_config.json

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      #--------------------------------------------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4
      #--------------------------------------------------------------------
      # Install Go
      #--------------------------------------------------------------------
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.2"
      #--------------------------------------------------------------------
      - run: go version
      #--------------------------------------------------------------------
      # client_secret.json
      #--------------------------------------------------------------------
      - name: Client secrets
        run: |
          echo '${{ secrets.GOOGLE_CLIENT_SECRET }}' > ./client_secret.json
      #--------------------------------------------------------------------
      - run: ./scripts/mod.download.sh
      #--------------------------------------------------------------------
      - run: ./scripts/mod.verify.sh
      #--------------------------------------------------------------------
      - run: ./scripts/mod.tidy.sh
      #--------------------------------------------------------------------
      - run: ./scripts/build.sh
      #--------------------------------------------------------------------
      - run: ./scripts/run.sh
      #--------------------------------------------------------------------
      - run: |
          ./dist/gcnf load --env unittest --sheet UnitTests
          ./dist/gcnf unload
